name: saudi_driving_theory_flutter
description: Offline Saudi Driving Theory Test app (Flutter migration)
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10
  google_mobile_ads: ^5.1.0
  intl: ^0.20.2
  collection: ^1.18.0
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "C:\\Users\\DELL\\Downloads\\icon\\icon.png.png"

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/data/
    - assets/data/licenseGuide/
    - assets/signs/
    - assets/ksa-signs/
